In [2]:
import numpy as np

In [6]:
np.__version__

'1.21.6'

In [9]:
fruits = ['mango', 'apple', 'pear','peach']
fruits

['mango', 'apple', 'pear', 'peach']

In [10]:
fruits = np.array(fruits)
fruits

array(['mango', 'apple', 'pear', 'peach'], dtype='<U5')

In [11]:
fruits.shape

(4,)

In [13]:
shape = (2,2)
fruits2d = fruits.reshape(shape)
fruits2d


array([['mango', 'apple'],
       ['pear', 'peach']], dtype='<U5')

In [14]:
fruits2d.shape

(2, 2)

In [59]:
seed = np.random.seed(28)
numbers = np.random.randint(1,11,10)
numbers

array([ 2, 10,  6,  7,  5,  1,  4,  8,  1,  4])

In [63]:
seed1 = np.random.seed(28)
a = np.random.randint(1,51,10)
b = np.random.randint(80,101,10)

print(a)
print(b)

[ 2  6 23 33  4 24 13  1 24 45]
[92 85 88 98 91 87 81 94 93 82]


In [97]:
sum_ab = a+b
div_ab = a/b
div_ba = b//a
print('The sum between a and b is: {}'.format(sum_ab))
print(' The div  between a and b is: {}'.format(div_ab))
print(' The interger div between b and a is: {}'.format(div_ba))


The sum between a and b is: [ 94  91 111 131  95 111  94  95 117 127]
 The div  between a and b is: [0.02173913 0.07058824 0.26136364 0.33673469 0.04395604 0.27586207
 0.16049383 0.0106383  0.25806452 0.54878049]
 The interger div between b and a is: [46 14  3  2 22  3  6 94  3  1]


In [101]:
mat_a = np.random.randint(1,11,25)
mat_a = mat_a.reshape((5,5))
mat_a.shape

(5, 5)

In [103]:
mat_b = np.random.randint(1,11,25)
mat_b = mat_b.reshape((5,5))
reate an array with zeros
mat_b.shape

(5, 5)

In [106]:
print(mat_a)
print()
print(mat_b)

[[ 3  5  9  4  9]
 [ 8  6  3 10  9]
 [ 6 10  7  2 10]
 [ 2  4  9  1  1]
 [ 1  6  6  2  3]]

[[ 2 10  2  9  1]
 [ 5  5  7  8  7]
 [ 3  6  8  5  7]
 [ 6  9  7  2 10]
 [ 4  1  7  7  8]]


In [107]:
np.dot(a,b)

15473

Create an array with zeros

In [3]:
zeros = np.zeros(28)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array with ones

In [4]:
ones = np.ones(40)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

Create an array with an intervals

In [6]:
intervals = np.arange(1,24)
intervals

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

Create an array sparsed

In [10]:
sparsed = np.linspace(1,5,10)
sparsed

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])